server:
  port: 8087
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null  # 序列化时过滤为null的属性
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.131:8848
  redis:
    host: localhost

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000