server:
  port: 8091
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null  # 序列化时过滤为null的属性
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.131:8848
  redis:
    host: localhost
  rabbitmq:
    host: 106.54.238.192
    username: gmall
    password: gmall
    virtual-host: /gmall

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000

gmall:
  jwt:
    pubKeyPath: rsa.pub # 公钥地址
    cookieName: GMALL_TOKEN # cookie的名称